# Generated by Django 4.0.3 on 2022-11-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.ImageField(default='default.jpg', null=True, upload_to='myimage'),
        ),
    ]
