# Generated by Django 4.0.3 on 2022-11-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.ImageField(null=True, upload_to='myimage'),
        ),
    ]
