# Generated by Django 4.0.3 on 2022-11-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
