# Generated by Django 4.0.3 on 2022-11-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
    ]
