# Generated by Django 4.0.3 on 2022-11-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_profile_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
